name: supermarket
description: "Flutter "
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  # Presentation
  shimmer: ^3.0.0
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7+1
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.6
  lazy_load_indexed_stack: ^1.2.1
  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.7
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  google_sign_in: ^6.3.0
  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sqflite_common_ffi: ^2.3.6
  sqlite3_flutter_libs: ^0.5.34
  # Security
  flutter_dotenv: ^5.2.1
  #General
  path: ^1.9.1
  image: ^4.5.4
  get_it: ^8.0.3
  crop_image: ^1.0.16
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  mobile_scanner: ^7.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700