// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6L6uaWCXQNsKBxHcYRHQ3oFlROi7T5oE',
    appId: '1:165444259387:ios:b6128e3d4f228907c6561e',
    messagingSenderId: '165444259387',
    projectId: 'supermarket-c0276',
    storageBucket: 'supermarket-c0276.firebasestorage.app',
    iosBundleId: 'com.example.supermarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDezM4G-AUidcRFi5HGdj2xlQVUqeD3Z_M',
    appId: '1:165444259387:web:13c5f22126e66985c6561e',
    messagingSenderId: '165444259387',
    projectId: 'supermarket-c0276',
    authDomain: 'supermarket-c0276.firebaseapp.com',
    storageBucket: 'supermarket-c0276.firebasestorage.app',
    measurementId: 'G-3TZ0LMFH4M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6L6uaWCXQNsKBxHcYRHQ3oFlROi7T5oE',
    appId: '1:165444259387:ios:b6128e3d4f228907c6561e',
    messagingSenderId: '165444259387',
    projectId: 'supermarket-c0276',
    storageBucket: 'supermarket-c0276.firebasestorage.app',
    iosBundleId: 'com.example.supermarket',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-pbmN1gucdro8-2TCNBi5EThtDBJYz8',
    appId: '1:165444259387:android:46730f9f973c44e3c6561e',
    messagingSenderId: '165444259387',
    projectId: 'supermarket-c0276',
    storageBucket: 'supermarket-c0276.firebasestorage.app',
  );
}
